export type TicketPriority = "low" | "normal" | "high" | "urgent";
export type TicketStatus = "new" | "processing" | "waiting" | "solved" | "closed";
export type Message = { id: string; from: "customer" | "agent"; text: string; time: string };
export type Ticket = { id: string; title: string; category: string; priority: TicketPriority; status: TicketStatus; owner: string; sla: string; followUp: string };
export type EnterpriseAccount = { id: string; name: string; short: string; industry: string; scale: string; tier: string; health: number; region: string };
export type Contact = { name: string; role: string; email: string; phone: string };
export type Subscription = { product: string; version: string; seats: number; expire: string; plan: string };
export type Conversation = { id: string; channel: "web" | "email" | "wecom"; subject: string; category: string; unread: number; lastTime: string; sla: string; slaTone: "safe" | "warning" | "danger"; account: EnterpriseAccount; contact: Contact; subscription: Subscription; messages: Message[]; tickets: Ticket[]; alert?: { title: string; text: string }; history: { title: string; meta: string }[] };
export type KnowledgeArticle = { id: string; title: string; summary: string; category: string; tags: string[]; views: number; reply: string };
export type Preference = { visibleModules: string[]; compact: boolean };

const baseHistory = [{ title: "账号权限配置咨询", meta: "已解决 · 2026-09-08" }, { title: "API 调用频率调整", meta: "已关闭 · 2026-08-21" }, { title: "季度服务回访", meta: "满意 · 2026-07-30" }];

export const conversations: Conversation[] = [
  { id: "CV-90821", channel: "wecom", subject: "管理员无法为新成员配置数据权限", category: "账号与权限", unread: 2, lastTime: "14:32", sla: "01:26:18", slaTone: "warning", account: { id: "AC-10072", name: "澜图数字科技", short: "澜", industry: "企业服务", scale: "500-999人", tier: "战略客户", health: 86, region: "上海" }, contact: { name: "周明远", role: "信息化负责人", email: "mingyuan.zhou@lantu.cn", phone: "138 **** 5026" }, subscription: { product: "Nexus Cloud 企业版", version: "企业增强版", seats: 320, expire: "2027-03-31", plan: "7×24 专属服务" }, alert: { title: "SLA 即将进入预警", text: "该客户为战略客户，首次响应剩余 1 小时 26 分钟" }, messages: [{ id: "m1", from: "customer", text: "你好，我们今天新入职了十几位同事，但管理员在批量配置数据权限时一直提示“策略冲突”。", time: "14:18" }, { id: "m2", from: "agent", text: "您好周老师，我是企业支持顾问林知夏。已经看到您反馈的权限配置问题，我先帮您核对一下当前组织的权限策略。", time: "14:20" }, { id: "m3", from: "customer", text: "好的。我们上午调整过部门层级，会不会和这个有关？现在比较着急，今天需要完成全部账号开通。", time: "14:22" }, { id: "m4", from: "agent", text: "有可能是部门层级变更后，原有角色的继承范围尚未刷新。请问提示异常的是同一个部门，还是多个部门？", time: "14:25" }, { id: "m5", from: "customer", text: "主要是华东销售一部和二部。我可以提供策略截图。", time: "14:32" }], tickets: [{ id: "TK-2381", title: "批量配置权限提示策略冲突", category: "账号与权限", priority: "high", status: "processing", owner: "林知夏", sla: "1小时 26分", followUp: "今天 16:00" }], history: baseHistory },
  { id: "CV-90817", channel: "email", subject: "开放平台接口间歇性返回 502", category: "开放平台", unread: 1, lastTime: "14:08", sla: "已超时 00:18", slaTone: "danger", account: { id: "AC-10451", name: "启源供应链", short: "启", industry: "供应链", scale: "1000-4999人", tier: "重点客户", health: 68, region: "深圳" }, contact: { name: "韩亦辰", role: "技术平台主管", email: "yichen.han@qiyuan.com", phone: "186 **** 1739" }, subscription: { product: "Nexus OpenAPI", version: "专业版", seats: 180, expire: "2026-12-18", plan: "5×8 标准服务" }, alert: { title: "SLA 已超时", text: "该问题在过去 7 天内重复反馈 3 次，请优先处理" }, messages: [{ id: "a1", from: "customer", text: "我们调用 /v2/company/sync 接口时仍然会间歇性返回 502，今天下午已经发生 6 次。", time: "13:42" }, { id: "a2", from: "agent", text: "收到。我正在核对请求链路，请提供最近一次异常的 request_id。", time: "13:46" }, { id: "a3", from: "customer", text: "request_id 是 req_9fd72c8a，麻烦尽快看看，已经影响数据同步。", time: "14:08" }], tickets: [{ id: "TK-2374", title: "开放平台同步接口间歇性 502", category: "接口异常", priority: "urgent", status: "processing", owner: "林知夏", sla: "已超时 18分", followUp: "立即" }], history: [{ title: "开放平台 502 异常", meta: "处理中 · 2026-09-15" }, ...baseHistory.slice(1)] },
  { id: "CV-90809", channel: "web", subject: "账单中的增购席位费用如何计算", category: "账单与合同", unread: 0, lastTime: "13:51", sla: "03:42:08", slaTone: "safe", account: { id: "AC-10884", name: "衡川生物医药", short: "衡", industry: "生物医药", scale: "200-499人", tier: "标准客户", health: 92, region: "杭州" }, contact: { name: "孟佳宁", role: "采购经理", email: "jianing.meng@hengchuan.cn", phone: "137 **** 8812" }, subscription: { product: "Nexus Cloud 协作版", version: "专业版", seats: 96, expire: "2027-01-15", plan: "5×8 标准服务" }, messages: [{ id: "b1", from: "customer", text: "您好，我们计划下个月增加 30 个账号，费用是按完整年度计算吗？", time: "13:44" }, { id: "b2", from: "agent", text: "您好，增购席位通常会按当前合同剩余周期折算，不需要支付完整年度费用。", time: "13:46" }, { id: "b3", from: "customer", text: "了解，那可以先给我们一个预估金额吗？", time: "13:51" }], tickets: [], history: baseHistory.slice(1) },
  { id: "CV-90796", channel: "wecom", subject: "单点登录证书即将过期", category: "系统配置", unread: 3, lastTime: "12:37", sla: "02:18:42", slaTone: "safe", account: { id: "AC-10116", name: "北辰智能制造", short: "北", industry: "智能制造", scale: "5000人以上", tier: "战略客户", health: 81, region: "苏州" }, contact: { name: "严树森", role: "IT 运维经理", email: "shusen.yan@beichen.com", phone: "139 **** 6520" }, subscription: { product: "Nexus Cloud 私有化版", version: "旗舰版", seats: 2400, expire: "2028-06-30", plan: "7×24 专属服务" }, messages: [{ id: "c1", from: "customer", text: "控制台提示 SSO 证书还有 10 天过期，请问更换会影响用户登录吗？", time: "12:37" }], tickets: [], history: baseHistory },
  { id: "CV-90782", channel: "email", subject: "导出报表字段与页面展示不一致", category: "产品使用", unread: 0, lastTime: "11:20", sla: "05:06:11", slaTone: "safe", account: { id: "AC-10917", name: "远山资本", short: "远", industry: "金融服务", scale: "100-199人", tier: "重点客户", health: 77, region: "北京" }, contact: { name: "许安然", role: "数据分析师", email: "anran.xu@yuanshan.cn", phone: "135 **** 4209" }, subscription: { product: "Nexus BI", version: "企业版", seats: 68, expire: "2026-11-30", plan: "5×8 优先服务" }, messages: [{ id: "d1", from: "customer", text: "导出的月度服务报表里缺少‘处理时长’字段，但页面上可以看到。", time: "11:20" }], tickets: [], history: baseHistory.slice(0, 2) }
];

export const knowledgeArticles: KnowledgeArticle[] = [
  { id: "KA-104", title: "组织架构调整后的权限刷新指南", summary: "说明部门层级变更后如何刷新角色继承范围并排查策略冲突。", category: "账号与权限", tags: ["权限", "组织架构", "策略冲突"], views: 286, reply: "根据您描述的情况，建议先在「组织与权限 > 权限策略」中执行一次权限范围刷新，再重新选择目标部门。如果仍提示冲突，请将策略名称和报错截图发给我，我会继续为您核查。" },
  { id: "KA-087", title: "OpenAPI 502 异常排查清单", summary: "包含 request_id、时间范围、请求区域及重试策略等必要信息。", category: "开放平台", tags: ["API", "502", "排查"], views: 412, reply: "为了快速定位 502 异常，请提供最近一次请求的 request_id、发生时间和调用区域。建议暂时采用指数退避策略重试，我们会根据链路记录进一步核查。" },
  { id: "KA-136", title: "合同周期内增购席位计费说明", summary: "介绍席位增购的剩余周期折算规则与报价流程。", category: "账单与合同", tags: ["增购", "席位", "计费"], views: 174, reply: "增购席位将按照当前合同的剩余有效期进行折算。您确认新增数量与预计生效日期后，我们可以生成准确的费用预估供您确认。" },
  { id: "KA-059", title: "无中断更新 SSO 证书", summary: "使用证书并行生效窗口完成安全更新。", category: "系统配置", tags: ["SSO", "证书", "登录"], views: 321, reply: "系统支持新旧 SSO 证书并行生效。建议先上传新证书并完成测试登录，确认无误后再停用旧证书，整个过程不会影响正常用户登录。" }
];

export const quickReplies = [
  { title: "正在为您核查", content: "收到，我正在为您核查相关配置和记录，预计 10 分钟内给您明确反馈，请稍等。" },
  { title: "补充排查信息", content: "为了更快定位问题，麻烦您提供问题发生时间、相关账号以及页面提示截图，我会继续跟进。" },
  { title: "问题已解决确认", content: "当前问题已完成处理，麻烦您刷新页面后再次尝试。如已恢复正常，请回复我确认，我会为您关闭本次服务记录。" },
  { title: "约定后续跟进", content: "该问题需要进一步核查，我已记录并会持续跟进，最晚于今天 18:00 前同步处理进展。" }
];
